// <auto-generated />
using System;
using Asistente.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asistente.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AsistenteIADbContext))]
    [Migration("20260901175102_AgregarProcesamientoDocumentalEtapa7")]
    partial class AgregarProcesamientoDocumentalEtapa7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Asistente.Domain.Entities.Asistente", b =>
                {
                    b.Property<int>("IdAsistente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsistente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Formalidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FormatoRespuesta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LongitudRespuesta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("int");

                    b.Property<string>("MensajeBienvenida")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ModeloIA")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Restricciones")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<decimal>("Temperatura")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("int");

                    b.HasKey("IdAsistente");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Asistente", (string)null);
                });

            modelBuilder.Entity("Asistente.Domain.Entities.AuditoriaActividad", b =>
                {
                    b.Property<int>("IdActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActividad"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DireccionIP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdDocumento")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdActividad");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdDocumento", "FechaHora");

                    b.ToTable("AuditoriaActividad", (string)null);
                });

            modelBuilder.Entity("Asistente.Domain.Entities.AuditoriaSesion", b =>
                {
                    b.Property<int>("IdSesion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSesion"));

                    b.Property<string>("DireccionIP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Navegador")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdSesion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("AuditoriaSesion", (string)null);
                });

            modelBuilder.Entity("Asistente.Domain.Entities.CategoriaDocumento", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategoria");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("CategoriaDocumento", (string)null);
                });

            modelBuilder.Entity("Asistente.Domain.Entities.ConfiguracionMemoria", b =>
                {
                    b.Property<int>("IdConfiguracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfiguracion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CantidadConversacionesVisibles")
                        .HasColumnType("int");

                    b.Property<int>("LongitudResumen")
                        .HasColumnType("int");

                    b.Property<int>("MaximoMensajesContexto")
                        .HasColumnType("int");

                    b.Property<int>("MaximoTokensContexto")
                        .HasColumnType("int");

                    b.HasKey("IdConfiguracion");

                    b.HasIndex("Activo")
                        .IsUnique()
                        .HasFilter("[Activo] = 1");

                    b.ToTable("ConfiguracionMemoria", (string)null);

                    b.HasData(
                        new
                        {
                            IdConfiguracion = 1,
                            Activo = true,
                            CantidadConversacionesVisibles = 20,
                            LongitudResumen = 800,
                            MaximoMensajesContexto = 10,
                            MaximoTokensContexto = 3000
                        });
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Conversacion", b =>
                {
                    b.Property<int>("IdConversacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConversacion"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUltimaActividad")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdAsistente")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("ResumenContexto")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TotalMensajes")
                        .HasColumnType("int");

                    b.Property<int>("TotalMensajesResumidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("IdConversacion");

                    b.HasIndex("IdAsistente");

                    b.HasIndex("IdUsuario", "Estado", "FechaUltimaActividad");

                    b.ToTable("Conversacion", (string)null);
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Documento", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumento"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EstadoProcesamiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UsuarioRegistro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VersionActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("IdDocumento");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("IdCategoria", "Estado", "FechaRegistro");

                    b.ToTable("Documento", (string)null);
                });

            modelBuilder.Entity("Asistente.Domain.Entities.DocumentoChunk", b =>
                {
                    b.Property<int>("IdChunk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChunk"));

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdDocumento")
                        .HasColumnType("int");

                    b.Property<int>("IdDocumentoProcesado")
                        .HasColumnType("int");

                    b.Property<int>("IdVersionDocumento")
                        .HasColumnType("int");

                    b.Property<int>("NumeroChunk")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("PaginaFinal")
                        .HasColumnType("int");

                    b.Property<int>("PaginaInicial")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCaracteres")
                        .HasColumnType("int");

                    b.HasKey("IdChunk");

                    b.HasIndex("IdVersionDocumento");

                    b.HasIndex("IdDocumento", "IdCategoria");

                    b.HasIndex("IdDocumentoProcesado", "NumeroChunk")
                        .IsUnique();

                    b.HasIndex("IdDocumentoProcesado", "Orden")
                        .IsUnique();

                    b.ToTable("DocumentoChunk", (string)null);
                });

            modelBuilder.Entity("Asistente.Domain.Entities.DocumentoProcesado", b =>
                {
                    b.Property<int>("IdDocumentoProcesado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumentoProcesado"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdVersionDocumento")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("TotalCaracteres")
                        .HasColumnType("int");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("int");

                    b.Property<int>("TotalPaginas")
                        .HasColumnType("int");

                    b.HasKey("IdDocumentoProcesado");

                    b.HasIndex("IdVersionDocumento")
                        .IsUnique();

                    b.HasIndex("Estado", "FechaInicio");

                    b.ToTable("DocumentoProcesado", (string)null);
                });

            modelBuilder.Entity("Asistente.Domain.Entities.DocumentoVersion", b =>
                {
                    b.Property<int>("IdVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVersion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashArchivo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("IdDocumento")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("NumeroVersion")
                        .HasColumnType("int");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("TamanoArchivo")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioCarga")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdVersion");

                    b.HasIndex("IdDocumento", "Activo")
                        .IsUnique()
                        .HasFilter("[Activo] = 1");

                    b.HasIndex("IdDocumento", "NumeroVersion")
                        .IsUnique();

                    b.ToTable("DocumentoVersion", (string)null);
                });

            modelBuilder.Entity("Asistente.Domain.Entities.HistorialPrompt", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorial"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPrompt")
                        .HasColumnType("int");

                    b.Property<string>("MotivoCambio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UsuarioModificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdPrompt");

                    b.ToTable("HistorialPrompt", (string)null);
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Mensaje", b =>
                {
                    b.Property<int>("IdMensaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMensaje"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdConversacion")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TiempoRespuestaMs")
                        .HasColumnType("int");

                    b.HasKey("IdMensaje");

                    b.HasIndex("IdConversacion");

                    b.ToTable("Mensaje", (string)null);
                });

            modelBuilder.Entity("Asistente.Domain.Entities.PromptSistema", b =>
                {
                    b.Property<int>("IdPrompt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrompt"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAsistente")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UsuarioCreacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("IdPrompt");

                    b.HasIndex("IdAsistente", "Activo")
                        .IsUnique()
                        .HasFilter("[Activo] = 1");

                    b.HasIndex("IdAsistente", "Version")
                        .IsUnique();

                    b.ToTable("PromptSistema", (string)null);
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Asistente.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario", "IdRol");

                    b.HasIndex("IdRol");

                    b.ToTable("UsuarioRol", (string)null);
                });

            modelBuilder.Entity("Asistente.Domain.Entities.AuditoriaActividad", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.Documento", "Documento")
                        .WithMany("ActividadesAuditoria")
                        .HasForeignKey("IdDocumento")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Asistente.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Actividades")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Documento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.AuditoriaSesion", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Sesiones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Conversacion", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.Asistente", "Asistente")
                        .WithMany()
                        .HasForeignKey("IdAsistente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Asistente.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Conversaciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asistente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Documento", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.CategoriaDocumento", "Categoria")
                        .WithMany("Documentos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.DocumentoChunk", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.DocumentoProcesado", "DocumentoProcesado")
                        .WithMany("Chunks")
                        .HasForeignKey("IdDocumentoProcesado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentoProcesado");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.DocumentoProcesado", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.DocumentoVersion", "VersionDocumento")
                        .WithOne("Procesamiento")
                        .HasForeignKey("Asistente.Domain.Entities.DocumentoProcesado", "IdVersionDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VersionDocumento");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.DocumentoVersion", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.Documento", "Documento")
                        .WithMany("Versiones")
                        .HasForeignKey("IdDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.HistorialPrompt", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.PromptSistema", "PromptSistema")
                        .WithMany("Historiales")
                        .HasForeignKey("IdPrompt")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PromptSistema");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Mensaje", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.Conversacion", "Conversacion")
                        .WithMany("Mensajes")
                        .HasForeignKey("IdConversacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversacion");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.PromptSistema", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.Asistente", "Asistente")
                        .WithMany("Prompts")
                        .HasForeignKey("IdAsistente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asistente");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("Asistente.Domain.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Asistente.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Asistente", b =>
                {
                    b.Navigation("Prompts");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.CategoriaDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Conversacion", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Documento", b =>
                {
                    b.Navigation("ActividadesAuditoria");

                    b.Navigation("Versiones");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.DocumentoProcesado", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.DocumentoVersion", b =>
                {
                    b.Navigation("Procesamiento");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.PromptSistema", b =>
                {
                    b.Navigation("Historiales");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Asistente.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Conversaciones");

                    b.Navigation("Sesiones");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
